BACKPORT: seccomp: add filter_count field for KernelSU
KernelSU requires struct seccomp to have atomic_t filter_count, but this field is missing on non-GKI kernels.
Adding the field fixes build errors such as: error: no member named 'filter_count' in 'struct seccomp'

Reference: tiann/KernelSU#2708

(cherry picked from commit 1948ac06bcc430d98c94968d9a6ce0fa46c16c47)
Co-authored-by: Selfmuser <109387456+selfmusing@users.noreply.github.com>
Signed-off-by: Bruce Teng <torai.d.l@outlook.com>